### PR TITLE
Honey for Android

### PR DESCRIPTION
**Pull request by TMueller83**
Adds new architectures `armv7-a` and `armv8-a` to the Makefile. Changes in the Makefile should not interfere with the remaining code and a single line in the source code is adapted for compatibility.

Compiling binaries for the Android platform is now very straight forward. Here is an example for the `armv8-a` architecture:

1. Download NDK from here: https://developer.android.com/ndk/downloads/index.html
2. Unzip NDK, for example to the directory `~/android-ndk-r21`
3. Enter the Honey `/src` directory and compile ARMv8-a binary:
     `$ make build ARCH=armv8-a COMP=ndk NDK=~/android-ndk-r21`

### CODE REVIEW

**Comment by MichaelB7** [comment]
Thanks -  I just released XIr1 - will start looking at this.  Will keep you posted.

**Comment by TMueller83** [comment]
Okay. Thank you for the release of Honey XIr1! Keep me updated if you have any questions or concerns regarding the pull request.

**Comment by MichaelB7** [comment]
Would be able to update the commit to XIr1?

Just pull the current honey branch into your commit branch and then push the commit branch up to your repo. The system should take care of the rest.  If you happen to get any merge conflicts , I can help you with those.

**Comment by TMueller83** [comment]
Yes, I think it is done.

**Pull request merged**
