### PR TITLE
Honey for Android

### PR DESCRIPTION
**Pull request by TMueller83**
- The Makefile is adapted for making it easy to compile binaries for Android using NDK.
- One minor change in the code (polybook.cpp) in oder to be able to compile with NDK.
- Added a build script to compile all 10 flavors automatically.
- Renamed the option UCI_Sleep to Sleep such that GUIs dont hide it.

### CODE REVIEW

**Comment by MichaelB7** [comment]
I’ll take a look and If I have any questions or concerns, will let you know. Thanks for doing this.

**Comment by TMueller83** [comment]
Hi @MichaelB7 thank you for checking the changes. Sorry if I messed something up with the commits. Im still learning how to use github correctly.

**Comment by MichaelB7** [comment]
@TMueller83 I cannot commit this PR "as is" .  Feel free to resubmit if you desire.

When it takes many commits to "get it right" , locally, you should rebase all of your commits down to one commit.  Also I will need to be able to see the changes to files , as it is now, a Makefile file is deleted and a Makefile is added in a separate commit.  Makes it  very hard for me to review , so I have to pass for now.  Github was much easier ( at least for me) to learn via the command line first rather than the desktop app.  Also, you want to use Honey's latest source for your commit and if the latest source is updated, you should pull those changes in before you submit.  I will definitely commit if you can make it easier for me to review.  I'm going to go ahead and  make the UCI_Sleep change.  I just refreshed the honey branch.

**Comment by TMueller83** [comment]
Hi @MichaelB7 yes, I realized that the commits were messy but I dind't know how to clean them. I will make a clean commit soon and create a new PR.

**Comment by MichaelB7** [comment]
Use “rebase -i HEAD~x” on your local where x is the number of commits you are squashing.  Google is your friend.

**Comment by MichaelB7** [comment]
Always squash YOUR new  commits before you push.

**Pull request closed without merging**
